config/routes.rb
Werewolf::Application.routes.draw do
   
  resources :villages do
   resources :games do
   member do
    patch 'beast'
    end
   end
  end
 resources :users do
   member do
     patch 'more'
   end
 end
 resources :sessions, only: [:new, :create, :destroy]
  root to: "static_pages#home" 
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
 match 'toggle', to: 'users#toggle',            via: 'patch' 
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :games
  
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 25 },
                   uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  def new
    @user = User.new
  end
  
  def show
   
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the werewolf game!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
   @user = User.find(params[:id]) 
  end
  # do not forget to edit app/assets/javascript/application.js to include bootstrap
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  
  def destroy
   User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url 
  end
  def more
  @user = User.find(params[:id])
  @user.admin = @user.toggle!(:admin)
  flash[:notice] = 'User updated admin'
  redirect_to users_url
 end
  private
  def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
  
  def signed_in_user
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
  def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  
 end

app/helpers/users_helper.rb
module UsersHelper
  def user_game(game)
  @user = current_user.id.joins(:games_users).where(:games_users => {:game_id => params[:id]})
  end
  
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<table class="horizontal_table" style="width: 100%; height: 10px;" border="1">
<tbody>

  <tr>
    <th width="20%"  >Name</th>
     
    <th width="35%" ></th>
    <th width="15%" ></th>
    <th width="15%"></th>
    <th width="15%"></th>
    
  </tr>
</tbody>
</table>

<div id="user-list">
<% @users.each do |user| %>
  <table class="horizontal_table" style="width: 100%; height: 10px;" border="1" cellspacing="0">
<tbody>


  <tr valign="top" class="<%= cycle('list-line-odd', 'list-line-even') %>" >
    <td width="20%" ><%= link_to user.name, user %></td>
    <% if current_user.admin? && !current_user?(user) %>
    <td width="35%"><%= user.email %></td>
    <td width="15%"><%= user.admin %></td>
    <td width="15%"><%= link_to 'Change admin rights', more_user_path(user), method: :patch,
                                  data: { confirm: "You sure this must be admin?" }%></td>
   <td width="15%" ><%= link_to 'X', user, method: :delete,
      data: { confirm: "You sure you want to remove user?" } %></td>
  </tr>
<% end %>
  <% end %>
</tbody>
</table>
</div>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<%= @user.name %>

<%= link_to 'Join Game', villages_path %>