config/routes.rb
Werewolf::Application.routes.draw do
   
  resources :villages do
   resources :games do
   member do
    patch 'beast'
    end
   end
  end
 resources :users do
   member do
     patch 'more'
   end
 end
 resources :sessions, only: [:new, :create, :destroy]
  root to: "static_pages#home" 
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
 match 'toggle', to: 'users#toggle',            via: 'patch' 
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
 
end

app/models/village.rb
class Village < ActiveRecord::Base
  has_many :games, dependent: :destroy
  accepts_nested_attributes_for :games
  
  def games_for_form
    collection = games.where(village_id: id)
    collection.any? ? collection : games.build
  end
  
  
end

app/controllers/villages_controller.rb
class VillagesController < ApplicationController
  before_action :set_village, only: [:show, :edit, :update, :destroy]

  def index
    @villages = Village.all
  end

  def show
  end

 
  def new
    @village = Village.new

  end

  def edit
  end

  
  def create
    @village = Village.new(village_params)

    respond_to do |format|
      if @village.save
        format.html { redirect_to @village, notice: 'Village was successfully created.' }
        format.json { render action: 'show', status: :created, location: @village }
      else
        format.html { render action: 'new' }
        format.json { render json: @village.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @village.update(village_params)
        format.html { redirect_to @village, notice: 'Village was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @village.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @village.destroy
    respond_to do |format|
      format.html { redirect_to villages_url }
      format.json { head :no_content }
    end
  end

  def games
    @user = User.all
    
  end
  def beast
  @village = Village.find(params[:village_id])
  @game = @village.games.find(params[:id])
  @game.werewolf = @game.toggle!(:werewolf)
  flash[:notice] = 'this werewolf'
  redirect_to village_path
 end
  
  
  
  private
    
    def set_village
      @village = Village.find(params[:id])
    end

    
    def village_params
      params.require(:village).permit(:name, games_attributes: [:id, :player])
    end
end

app/helpers/villages_helper.rb
module VillagesHelper
  def beast
  @village = Village.find(params[:village_id])
  @game = @village.games.find(params[:game_id])
  @game.toggle!(:werewolf)
  flash[:notice] = 'this werewolf'
  redirect_to village_path
 end
  
  
end

app/views/villages/_detail.html.erb
<%= @village.name %>
<%= render @village.detail %>

app/views/villages/_form.html.erb
<%= form_for(@village) do |f| %>
  <% if @village.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@village.errors.count, "error") %> prohibited this village from being saved:</h2>

      <ul>
      <% @village.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/villages/edit.html.erb
<h1>Editing village</h1>

<%= render 'form' %>

<%= link_to 'Show', @village %> |
<%= link_to 'Back', villages_path %>

app/views/villages/index.html.erb
<h1>Listing villages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @villages.each do |village| %>
      <tr>
        <td><%= village.name %></td>
        <td><%= link_to 'Show', village %></td>
        <td><%= link_to 'Edit', edit_village_path(village) %></td>
        <td><%= link_to 'Destroy', village, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Village', new_village_path %>

app/views/villages/new.html.erb
<h1>New village</h1>

<%= render 'form' %>

<%= link_to 'Back', villages_path %>

app/views/villages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @village.name %>
</p>
<table class="horizontal_table" style="width: 100%; height: 10px;" border="1">
<tbody>

  <tr>
    <th width="40%">Player </th>
    <th width="10">user#</th>
    <th width="15%">alive</th>
<% if current_user.admin? %>
    <th width="15%">werewolf</th>
    <th width="10%">against</th>
   <th width="10%">voted</th>
   <% end %>
  </tr>
</tbody>
</table>

<%= render @village.games %>

<b>Add new player  </b>

<%= render 'games/form' %>

<%= link_to 'Edit', edit_village_path(@village) %> |
<%= link_to 'Back', villages_path %>